#!/usr/bin/env python3
"""Write terraform/peers.auto.tfvars from `terraform output -json` on stdin.

Cloud Run URLs are opaque and unknowable before creation, so pass 2 of the apply
feeds them back in. This file is gitignored: it contains the public URLs."""
import json
import sys

out = json.load(sys.stdin)
urls = out["actual_urls"]["value"]
web = out["web_url"]["value"]

with open("peers.auto.tfvars", "w") as f:
    f.write("# GENERATED by scripts/deploy.sh -- gitignored, contains public URLs.\n")
    f.write("peer_urls = {\n")
    for region, url in sorted(urls.items()):
        f.write('  "%s" = "%s"\n' % (region, url))
    f.write("}\n")
    f.write('web_url = "%s"\n' % web)

print("  wrote %d hop URLs + web url" % len(urls))
